### ISSUE TITLE
Implementation strategy for getOriginalProperty and friends is mostly wishful thinking

### ISSUE THREAD

**Issue by bzbarsky** [domenic/get-originals#10]
1) I'm not sure what "unwrap to the underlying C++/Rust property/method" means.  The argument is a string name.  What needs to happen is that the object (more on this below) and then its "original prototype chain" (a concept that probably needs to be defined) needs to be searched for the given name.

The object itself needs to be considered if we want this to work with something like `event.isTrusted`.  And no, you can't just get that without this API by relying on its unforgeability, because you don't know whether your `event` is actually an Event.

After that you need to basically walk what the prototype chain would have been if no one had ever messed with any [[Prototype]] slots and for each thing look for the original whatever with the given name on it.   Once _that's_ done you can start thinking about getting to the underlying C++/Rust/whatever function...

2) For JavaScript objects, it's much the same issue, though they may not have any own properties.  Yes, you need to determine the brand, and then walk the corresponding proto chain looking for the right thing.  It's possible to do this without switches, but it costs memory.  Might not be too bad, at least in SpiderMonkey...

**Comment by domenic** [comment]
You're right, when I think about this harder, it doesn't make as much as sense. I was extrapolating too much from our earlier discussions and from my own work on jsdom's JS-wrapping-JS Web IDL wrappers.

Could you give a bit more detail about the strategy you're thinking of, closer to the implementation level? What I'm hearing is something like:

1. Look at `target`'s brand (e.g. its interface `i`), and use that to determine `target`'s original [[Prototype]], `p`.
2. If `p` is null, fail.
3. See if `p` contains the property/method given by `name`.
   1. If so, invoke the original version of it on `target`
   2. If not, set `i` to whatever `i` inherits from, and `p` to the corresponding prototype, then return to step 2.

Does this sound right? The non-obvious operations here are:

- Object -> brand
- Brand -> prototype
- Prototype -> original property/method/etc.
- Prototype/brand -> what it inherits from

Help would be appreciated on knowing if these non-obvious operations are realistically implementable, at least in Gecko/SpiderMonkey.

**Comment by bzbarsky** [comment]
> If p is null, fail.

Not quite, because of unforgeable properties and the global, which have stuff living directly on the instance.  But yes, in general your summary looks right to me.

In terms of Gecko's implementation, we have the following information for webidl objects (ES objects are a totally different issue and will need a lot more work for all this stuff):

1)  We can go from an instance object to a struct describing the branding of that object.
2)  The branding struct has a pointer to a function to call to get the "original prototype".  Note that this is strictly branding-based: if you have a subclass of `HTMLAnchorElement`, the "original prototype" will be the original `HTMLAnchorElement.prototype`.
3)  The branding struct also has a pointer to data tables describing all the attributes and operations defined for that interface.  That includes static, non-static, unforgeable, constants, etc.  To a first approximation, these data tables are linear lists of entries containing the property name, a pointer to the C++ function to use a the implementation of the ES Function implementing the method/getter/setter, and some metadata about whether the property is readonly/configurable/etc in the ES sense.
4)  We can go from a WebIDL prototype object to a different branding struct.
5)  The prototype's branding struct has a pointer to a function to get _its_ default prototype.
6)  The prototype's branding struct has a pointer to the data tables for its interface (same pointer as the instance, if this is a most-derived prototype).
7)  WebIDL constructors likewise have a branding struct with information about _their_ prototype (e.g. `HTMLAnchorElement.__proto__ === HTMLElement`) and a pointer to those same data tables.

Oh, and we can tell whether a given object is a webidl instance/prototype/constructor.  Namespaces work exactly like constructors internally; they just have `Object.prototype` instead of `Function.prototype` as their proto and different toString and call behavior.  They still have the branding bits.

So I think we can implement all four of the non-obvious operations; the only caveat is that without additional caching somewhere the "Prototype -> original property/method/etc" bit is O(N) because it needs to scan the data table.
