### ISSUE TITLE
Originals through built-in modules

### ISSUE THREAD

**Issue by littledan** [domenic/get-originals#19]
I've heard suggestions from @lukewagner and @mattijs that we could provide access to a separate, frozen copy of built-ins through modules. Has anyone written up this idea? Should we develop it further in this repo or another one?

**Comment by ljharb** [comment]
I think we'd still need a way for polyfills/shims to, in advance of that access and of the freezing, add in missing behavior, repair/replace broken behavior, and deny access to undesired things (annex b, high-resolution timers, etc).

**Comment by littledan** [comment]
Agreed that we need some kinds of virtualization. I see this as working best with import-maps, which could enable these changes regardless of whether the approach in this repo or this issue are taken. Do you see any holes with that approach?

**Comment by ljharb** [comment]
If non-syntax things are always deniable/replaceable/patchable/virtualizable via import maps, that does seem like it might work.

**Comment by littledan** [comment]
@ljharb Does the current import-maps proposal meet this requirement for you?

**Comment by ljharb** [comment]
I *think* so - it remains to be seen how it will interact with this proposal.

**Comment by mattijs** [comment]
I have not incorporated the idea as part of the standard library proposal, but I intend to.

**Comment by lukewagner** [comment]
:100: :heart:
