### ISSUE TITLE
Bikeshedding: is the name "original" right?

### ISSUE THREAD

**Issue by domenic** [domenic/get-originals#2]
Various properties may change their _values_ over time, so we're not getting their "original" values. In fact, the values may change over time Is this confusing?

For example, consider

```js
const o_document = getOriginalProperty(originalSelf, "document");

const activeElement1 = getOriginalProperty(o_document, "activeElement");

// ... later ...
const activeElement2 = getOriginalProperty(o_document, "activeElement");
```

in this example, `activeElement2` may be a different value than `activeElement1`.

**Comment by ljharb** [comment]
hmm - in this case, it seems like you're actually trying to get the original getter, and then evaluate that?

**Comment by benjamingr** [comment]
I like the name original.

**Comment by domenic** [comment]
Note that the new API no longer has any publicly-exposed "original" word anywhere, with the entry point being `"std:global/X"`. So this is now just about the repository/project name, which I think doesn't really matter. (Especially since this will just merge into the Web IDL spec.)

I'll close this.
