### ISSUE TITLE
Proposed implementation strategy for getOriginalConstructor is not necessarily viable

### ISSUE THREAD

**Issue by bzbarsky** [domenic/get-originals#4]
The strategy makes all sorts of assumptions that need not hold (and don't hold in some implementations).  For example, it assumes that all the objects are actually created at Realm creation time.  In practice, in various implementations the objects can be created lazily.

Furthermore, Realm creation is fairly performance-sensitive; adding more things to that path is not likely to be acceptable.

In practice, I would expect implementation strategies here to vary widely by engine and to have quite varied performance and memory characteristics (most simply, getOriginalConstructor may well end up needing to be O(N) in number of constructors, depending).

**Comment by domenic** [comment]
Thanks. The implementation strategy here was definitely among the more speculative. It would be nice if there was a scheme that avoided O(N) behavior though :-/.

Is there any other API you can envision for getting access to the original constructors that would be easier to implement with good performance and memory characteristics?

**Comment by bzbarsky** [comment]
I haven't though of anything yet.

To be clear, in Gecko this is not O(N) for webidl things: there is a hashtable that maps names to "create this thing" C++ function pointers.  I'm just saying this is not the only possible implementation and that memory/speed tradeoffs may matter here for other implementations or for Gecko in the future, depending on the size of this hashtable and how broadly it can be shared (e.g. across processes).
