### ISSUE TITLE
The "except the global object" restriction on getOriginalProperty and friends seems wrong

### ISSUE THREAD

**Issue by bzbarsky** [domenic/get-originals#7]
The first bullet point under there says:

> Any Web IDL platform object, except the global object;

but the examples do `getOriginalProperty(originalSelf, "close");` and `originalSelf` is "the global object`.  The examples look right and the first bullet wrong, to me.

**Comment by domenic** [comment]
Thanks, this was leftover from a previous revision, and just a bug. Will remove.
